### ISSUE TITLE
Moar Testing!

### ISSUE THREAD

**Issue by Zelly9191** [crazysnailboy/UncraftingTable#5]
Alright here is what i know so far.

Every version:
-"All in one" needs more chest compatibility (ender chest trapped chest)
-Config does not display defaults
-Uncrafting never uses the max level (I think? I'm not sure.)
-Changes do not load from "mod options" from in game menu. Requires exit and world reload.
-Strange effects happen with Uncrafting standard:3 max:9 meathead:2 (not tested in 1.11)
-Either i or you need to test what happens when max level is above the standard level.

1.11
-In game config does not apply to the actual config and it changes nothing.

Sugestions:
-Make a suggestion area under issues on GitHub
-Config needs an example for item Exclusion
-"All in one" Should have a better achievement description

**Comment by Zelly9191** [comment]
-Strange effects happen with Uncrafting standard:3 max:9 meathead:2 (not tested in 1.11)

Additional xp is being added on top of the max level instead of the standard level when uncrafting damaged items. happens with default levels as well.  Also opening the uncrafting gui will show the standard level required until an item is placed in and removed. It will then show 0 levels and works correctly from there. These will need fixing before I can update every screenshot. Thanks again!

**Comment by crazysnailboy** [comment]
_- Config does not display defaults_
It does - it's included in the tooltip when you hover over the label

_- Uncrafting never uses the max level (I think? I'm not sure.)_
No it never quite will. The max level is used by the Xell75's & Zenen calculation, and is applied to the damage percentage of the item. So you'd need a 100% damaged item to get to the max level.

_- Changes do not load from "mod options" from in game menu. Requires exit and world reload._
Yes, this is true. That was a feature which was never fully implemented in Forge, because of the difficulties of showing options for multiple mods from that screen.

_- Strange effects happen with Uncrafting standard:3 max:9 meathead:2_
Do you mean method 2? There is no method 2 - it should be 0 (jglrxavpok) or 1 (Xell75's & Zenen)

_- In game config does not apply to the actual config and it changes nothing. (1.11)_
Are you sure? I just tested this myself and it works as expected in 1.7-pre3

**Comment by Zelly9191** [comment]
Sorry i should have been more clear. In the config out of game it no longer displays the default like it use to. On 100% damaged weapons with 1 durability left it will not use max level. This can be tested by hitting a gold sword on dirt until 2 durability and hitting a mob one time to bring it to one. (however this is not a huge deal i can always bump the max level by one and that works.) Sorry! I didn't know that about the mod options and my bad I meant method 1.  I can retest the config thing in 1.11 and see why it was occurring for me. Sorry again I should have been more clear the first time. Hopefully this cleared things up a bit.

**Comment by Zelly9191** [comment]
I'm sure someone would have reported it if it was an issue. maybe i was just going crazy. 9304 downloads woo!
