### ISSUE TITLE
1.10.2 Version: Iron Chest Uncrafting Crash

### ISSUE THREAD

**Issue by MokahTGS** [crazysnailboy/UncraftingTable#9]
Getting a crash when uncrafting an Iron Chest from the iron chest mod.  The gold chest uncrafts fine.

http://pastebin.com/B8MRVxtV

**Comment by crazysnailboy** [comment]
Thanks for letting me know! I'll get that fixed and get a new version uploaded

**Comment by crazysnailboy** [comment]
Hi,

The problem was related to an ore dictionary recipe Iron Chests registers so that the chest can be made using Refined Iron from IC2. The Uncrafting Table was crashing because it was expecting to find an item in the ore dictionary for refined iron where there was none.

This is resolved in 1.6.1-pre3, which you get [here](https://github.com/crazysnailboy/uncraftingTable/releases/tag/v1.6.1-pre3-1.10.2).

Thanks again for pointing this out :)
